// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Play struct {
	Bet                  int32    `protobuf:"varint,1,opt,name=Bet,proto3" json:"Bet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Play) Reset()         { *m = Play{} }
func (m *Play) String() string { return proto.CompactTextString(m) }
func (*Play) ProtoMessage()    {}
func (*Play) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *Play) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Play.Unmarshal(m, b)
}
func (m *Play) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Play.Marshal(b, m, deterministic)
}
func (m *Play) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Play.Merge(m, src)
}
func (m *Play) XXX_Size() int {
	return xxx_messageInfo_Play.Size(m)
}
func (m *Play) XXX_DiscardUnknown() {
	xxx_messageInfo_Play.DiscardUnknown(m)
}

var xxx_messageInfo_Play proto.InternalMessageInfo

func (m *Play) GetBet() int32 {
	if m != nil {
		return m.Bet
	}
	return 0
}

//盤面
type Result struct {
	Table                []int32  `protobuf:"varint,1,rep,packed,name=Table,proto3" json:"Table,omitempty"`
	Paylinesnum          []int32  `protobuf:"varint,2,rep,packed,name=Paylinesnum,proto3" json:"Paylinesnum,omitempty"`
	Paylinescount        []int32  `protobuf:"varint,3,rep,packed,name=Paylinescount,proto3" json:"Paylinescount,omitempty"`
	Odds                 int32    `protobuf:"varint,4,opt,name=Odds,proto3" json:"Odds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetTable() []int32 {
	if m != nil {
		return m.Table
	}
	return nil
}

func (m *Result) GetPaylinesnum() []int32 {
	if m != nil {
		return m.Paylinesnum
	}
	return nil
}

func (m *Result) GetPaylinescount() []int32 {
	if m != nil {
		return m.Paylinescount
	}
	return nil
}

func (m *Result) GetOdds() int32 {
	if m != nil {
		return m.Odds
	}
	return 0
}

func init() {
	proto.RegisterType((*Play)(nil), "pb.Play")
	proto.RegisterType((*Result)(nil), "pb.Result")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2d, 0x4e, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x92, 0xe0, 0x62, 0x09, 0xc8, 0x49,
	0xac, 0x14, 0x12, 0xe0, 0x62, 0x76, 0x4a, 0x2d, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x02,
	0x31, 0x95, 0xaa, 0xb8, 0xd8, 0x82, 0x52, 0x8b, 0x4b, 0x73, 0x4a, 0x84, 0x44, 0xb8, 0x58, 0x43,
	0x12, 0x93, 0x72, 0x52, 0x25, 0x18, 0x15, 0x98, 0x35, 0x58, 0x83, 0x20, 0x1c, 0x21, 0x05, 0x2e,
	0xee, 0x80, 0xc4, 0xca, 0x9c, 0xcc, 0xbc, 0xd4, 0xe2, 0xbc, 0xd2, 0x5c, 0x09, 0x26, 0xb0, 0x1c,
	0xb2, 0x90, 0x90, 0x0a, 0x17, 0x2f, 0x8c, 0x9b, 0x9c, 0x5f, 0x9a, 0x57, 0x22, 0xc1, 0x0c, 0x56,
	0x83, 0x2a, 0x28, 0x24, 0xc4, 0xc5, 0xe2, 0x9f, 0x92, 0x52, 0x2c, 0xc1, 0x02, 0xb6, 0x1a, 0xcc,
	0x4e, 0x62, 0x03, 0x3b, 0xd0, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xff, 0x2f, 0x42, 0xb9, 0xad,
	0x00, 0x00, 0x00,
}
